version: "3"

services:
  db:
    image: mysql:8.0.22
    ports:
      - "3306:3306"  
    # expose:                     # useful for testing, external clients can connect and execute queries
    #   - "3306"                  # can be disabled 
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  project:
    depends_on:
      - db
    restart: on-failure         # ugly hack that is needed because db signals availability before it actually is
                                # real solution would be to have mechanism/script that checks for db connectivity and then start spring-boot app
                                # there are also tools that perform this kind of checks
                                # it is expected that spring-boot craches during first startup
    image: stupar/project
    ports: 
      - "8080:8080"
      - "8443:8443"
    expose:
      - "8081"
      - "8444"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/project
      - SPRING_PROFILES_ACTIVE=https             # https | http
      - SERVER_HTTP_PORT=8080
      - SERVER_HTTPS_PORT=8443                   # not relevant if http profile is active
      - SERVER_SECURITY_USERS_FILE=/users.txt    # /users.txt is part of docker image / see Dockerfile